events {
    worker_connections 2048;
}

http {

upstream backend {
    server backend:8888;
}

server {

    listen 88;
    client_max_body_size 5m;

    location /api {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect default;
    }
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
}
}